#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        EventStation.py
#
#  Project :     EventStation
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      cosimo.volpicelli$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["EventStation", "EventStationClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(EventStation.additionnal_import) ENABLED START -----#
import random
from datetime import datetime
#----- PROTECTED REGION END -----#	//	EventStation.additionnal_import

# Device States Description
# No states for this device


class EventStation (PyTango.Device_4Impl):
    """Manage and detect the event on the station"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(EventStation.global_variables) ENABLED START -----#
    start= datetime.now()
    
    #----- PROTECTED REGION END -----#	//	EventStation.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        EventStation.init_device(self)
        #----- PROTECTED REGION ID(EventStation.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	EventStation.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(EventStation.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	EventStation.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_NewDirectory_read = 0
        self.set_change_event("NewDirectory", True, False)
        #----- PROTECTED REGION ID(EventStation.init_device) ENABLED START -----#
        print("init_device",str(datetime.now()) )
        #----- PROTECTED REGION END -----#	//	EventStation.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(EventStation.always_executed_hook) ENABLED START -----#
        print("always_execute",str(datetime.now()),self.attr_NewDirectory_read )   
#        self.attr_NewDirectory_read = 0
        #----- PROTECTED REGION END -----#	//	EventStation.always_executed_hook

    # -------------------------------------------------------------------------
    #    EventStation read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_NewDirectory(self, attr):
        self.debug_stream("In read_NewDirectory()")
        #----- PROTECTED REGION ID(EventStation.NewDirectory_read) ENABLED START -----#
        print(self.get_name(),"::read_NewDirectory")
#        print("read_NewDirectory",str(datetime.now()) )
#        print("read_NewDirectory",self.attr_NewDirectory_read)
        if self.attr_NewDirectory_read > 60:
                print("read_NewDirectory MAGGIORE DI 90")
#                self.push_change_event("NewDirectory",self.attr_NewDirectory_read)
#                attr.set_value(self.attr_NewDirectory_read)
        else:
                #self.attr_NewDirectory_read=0
                attr.set_value(None)
        
        #----- PROTECTED REGION END -----#	//	EventStation.NewDirectory_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(EventStation.read_attr_hardware) ENABLED START -----#
        print("read_attr_hardware",str(datetime.now()) ) 
#        print(data)
        #----- PROTECTED REGION END -----#	//	EventStation.read_attr_hardware


    # -------------------------------------------------------------------------
    #    EventStation command methods
    # -------------------------------------------------------------------------
    
    def EventDetected(self):
        """ Check if directory exist
        """
        self.debug_stream("In EventDetected()")
        #----- PROTECTED REGION ID(EventStation.EventDetected) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	EventStation.EventDetected
        

    #----- PROTECTED REGION ID(EventStation.programmer_methods) ENABLED START -----#
        tt = datetime.now()
        delta = tt - self.start
        print("DELTA",delta.seconds)
        self.start= tt
        #print("SONO QUI")    
#        print("SONO QUI",str(datetime.now()) )
        num=random.randint(1,101)
        print (num)
#        self.attr_NewDirectory_read = num
        if num > 60 :
              self.attr_NewDirectory_read = num
              self.push_change_event("NewDirectory",num) 
#             print("EventDetectd",str(datetime.now()) )
#             print("PUSH NewDirectory")
        
    #----- PROTECTED REGION END -----#	//	EventStation.programmer_methods

class EventStationClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(EventStation.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	EventStation.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'data_path':
            [PyTango.DevString, 
            "path della directory events",
            ["/prismatest"] ],
        }


    #    Command definitions
    cmd_list = {
        'EventDetected':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"],
            {
                'Polling period': "3000",
            } ],
        }


    #    Attribute definitions
    attr_list = {
        'NewDirectory':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'abs_change': "90",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(EventStationClass, EventStation, 'EventStation')
        #----- PROTECTED REGION ID(EventStation.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	EventStation.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
